In [13]:
import numpy as np
import numpy.linalg as lin
import torch

In [17]:
tensor_a = torch.FloatTensor([[0, 1],[1, 1],[2, 1],[3, 1]])
tensor_b = torch.FloatTensor([[-1],[0.2],[0.9],[2.1]])
print(tensor_a)
print(tensor_b)
tensor_a_inver = lin.pinv(tensor_a) # A행렬의 유사역행렬을 구함
print(tensor_a_inver)
result = np.matmul(tensor_a_inver, tensor_b) # A의 유사역행렬과 B행렬을 곱셈연산 함
print(result) # 결과 출력

# Ax = B 행렬에서 x= (A^-1)B가 된다.
#이를 풀기위해 A의 역행렬을 구해야하지만 정방행렬이 아니기 때문에 유사역행렬을 구한후 B행렬과 곱셈연산을 하여 값을 구하였다.

tensor([[0., 1.],
        [1., 1.],
        [2., 1.],
        [3., 1.]])
tensor([[-1.0000],
        [ 0.2000],
        [ 0.9000],
        [ 2.1000]])
[[-0.29999998 -0.09999999  0.09999999  0.29999998]
 [ 0.6999999   0.39999998  0.09999999 -0.2       ]]
tensor([[ 1.0000],
        [-0.9500]])
