2020732078_김대원 3월 21일 직접 작성하였습니다.

##Linear Regression란##
회귀 문제는 주어진 데이터포인트  x
 에 해당하는 실제 값으로 주어지는 타겟  y
 를 예측하는 모델
> Supervised Learning 중, 비교적 쉽고 간단한 문제

#예제#

| X | Y |
| :----: | :----: |
| 1.0 | 1.0 |
| 2.0 | 2.0 |
| 3.0 | 3.0 |

y= ax + b 의 선형 모델

#Imports

In [24]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as func
import torch.optim as opt

#코랩에서 내 구글 드라이브 연결
from google.colab import drive
drive.mount('/content/drive')

#Seed를 고정한다.
torch.manual_seed(1)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


#Data loading

In [25]:
# x_train과 y_train의 데이터 셋을 직접 설정
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[1],[2],[3]])

print(x_train)
print(x_train.shape)
print(y_train)
print(y_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])
tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


#Hypothesis and Cost
$$
Yhypo = H(x) = w*x + b
$$
선형임을 가정한 경우 위 수식을 만족
data가 3개인 경우  
$\begin{bmatrix}y1\\y2\\y3 \end{bmatrix} = w * \begin{bmatrix}x1\\x2\\x3 \end{bmatrix}+b$  
이를 만족하는 w와 b를 구해야 한다
Cost function으로 Mean-Square-Error를 이용
$\frac{1}{N}\displaystyle\sum_{n=0}^{n=N}{(y_h-y_t)^2}$


In [26]:

# 모델을 초기화하고 ()안에 입력 dim과 출력 dim을 입력
model = nn.Linear(1,1)

# Hypothesis를 정의
y_hypo = model(x_train)
print(list(model.parameters()))
print(y_hypo)

#Cost 즉 Mean Sqaure Error를 계산
cost = func.mse_loss(y_hypo, y_train)
print(cost)


[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]
tensor([[0.0739],
        [0.5891],
        [1.1044]], grad_fn=<AddmmBackward0>)
tensor(2.1471, grad_fn=<MseLossBackward0>)


# Cost Optimization
* Optimizer로 stochastic gradient descent를 이용

In [27]:
# optimizer 설정 learning rate를 0.01로 설정

optimizer = opt.SGD(model.parameters(), lr=0.01)
#반복문
for epoch in range(1000):
  # cost와 mse_loss 정의
  y_hypo = model(x_train)
  cost = func.mse_loss(y_hypo, y_train)

  # cost를 통해 모델을 업데이트
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  # 반복 100회 마다 결과를 출력
  if epoch % 100 == 99:
    params = list(model.parameters())
    w = params[0].item()
    b = params[1].item()
    print('Epoch {:4d}/{} w: {:.3f} b : {: .3f} Cost: {:.6f}'.format( epoch+1, 1000, w,b,cost.item()))


Epoch  100/1000 w: 1.066 b : -0.150 Cost: 0.003255
Epoch  200/1000 w: 1.052 b : -0.118 Cost: 0.002011
Epoch  300/1000 w: 1.041 b : -0.093 Cost: 0.001243
Epoch  400/1000 w: 1.032 b : -0.073 Cost: 0.000768
Epoch  500/1000 w: 1.025 b : -0.057 Cost: 0.000475
Epoch  600/1000 w: 1.020 b : -0.045 Cost: 0.000293
Epoch  700/1000 w: 1.016 b : -0.035 Cost: 0.000181
Epoch  800/1000 w: 1.012 b : -0.028 Cost: 0.000112
Epoch  900/1000 w: 1.010 b : -0.022 Cost: 0.000069
Epoch 1000/1000 w: 1.008 b : -0.017 Cost: 0.000043


# Multivariable Linear Regression
$$
y_h = H(x) = W*x + b
$$
선형임을 가정한 경우 위 수식을 만족

$y_h  = \begin{bmatrix}w1&w2&w3\\ \end{bmatrix} * \begin{bmatrix}x1\\x2\\x3 \end{bmatrix}+\begin{bmatrix}b\\ \end{bmatrix}$  

MSE cost를 최소화하는 
와 
를 구해야 한다


In [28]:
dataset = np.loadtxt('/content/drive/MyDrive/Colab Notebooks/data_linear_regression.csv', delimiter=',', dtype=np.float32)
np.random.shuffle(dataset)

x_train = torch.FloatTensor(dataset[:,:-1])
y_train = torch.FloatTensor(dataset[:,[-1]])

model = nn.Linear(3,1)

optimizer = opt.SGD(model.parameters(), lr=0.00001)

for epoch in range(1000):
  y_hypo = model(x_train)
  cost = func.mse_loss(y_hypo, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()
  if epoch % 100 == 99:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch+1, 1000, cost.item()))

print(y_hypo-y_train)

Epoch  100/1000 Cost: 27.945959
Epoch  200/1000 Cost: 26.145174
Epoch  300/1000 Cost: 24.495071
Epoch  400/1000 Cost: 22.982965
Epoch  500/1000 Cost: 21.597174
Epoch  600/1000 Cost: 20.327076
Epoch  700/1000 Cost: 19.162939
Epoch  800/1000 Cost: 18.095854
Epoch  900/1000 Cost: 17.117643
Epoch 1000/1000 Cost: 16.220892
tensor([[ 2.7283],
        [ 1.7373],
        [ 3.7314],
        [-0.7313],
        [-1.6001],
        [ 5.1373],
        [-4.2887],
        [-0.5103],
        [ 3.1929],
        [-0.2428],
        [ 2.9134],
        [-6.4294],
        [ 5.7041],
        [-4.5285],
        [-5.1900],
        [ 3.0094],
        [ 2.0861],
        [ 2.5786],
        [ 8.3312],
        [-2.3550],
        [-2.7923],
        [-8.5924],
        [-3.7555],
        [ 1.0688],
        [-1.0264]], grad_fn=<SubBackward0>)


5. 과제
풀고 있지만 아직 못 풀었습니다.ㅜㅜ
결과만 추가 제출 가능한가요?